debug: true

logging:
  level:
    com.hcl: debug
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: none
# Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
# Because detection is disabled you have to set correct dialect by hand.
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect    
  datasource:
    url: jdbc:postgresql://ec2-23-21-238-28.compute-1.amazonaws.com:5432/d798ju9hj2tj13?sslmode=require
    username: xplqosatmcvrum
    password: 56bc19cc98debba854ca33153b0a3f133d5cd79b4e0783fc989020c2370ba590
    #url: jdbc:postgresql://localhost:5433/hiroku
    #username: hiroku
    #password: hiroku